version: "3.8"

services:
  frontend: # service name, can be anything see section below
    depends_on:
      - backend
    build: ./frontend # folder where the dockerfile is located
    ports: # mapping port of host:container
      - 3000:3000

  backend:
    depends_on:
      - db
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly # env variable, see variable sunbstitution link above as well
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial # pulling image from dockerhub instead of bulding from dockerfile
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly: # No value, just property/volume name
