version: "3.8"

services:
  frontend: # service name, can be anything see section below
    depends_on:
      - backend
    build: ./frontend # folder where the dockerfile is located
    ports: # mapping port of host:container
      - 3000:3000
    # volumes:
    #   - ./frontend:/app:z

  # took out `volume` cause it did not work
  # keep it if it does, cause tests need live updates too
  frontend-tests: # service name, can be anything see section below
    depends_on:
      - frontend
    image: 3-vidly_frontend # build from fe image
    command: npm test

  backend:
    depends_on:
      - db
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly # env variable, see variable sunbstitution link above as well
    # volumes:
    #   - ./backend:/app:z # volume mapping for live updates; <relative path in host>:<container path>
    command: ./docker-entrypoint.sh # ovewrites CMD of the dockerfile

  # took out `volume` cause it did not work
  # keep it if it does, cause tests need live updates too
  backend-tests:
    depends_on:
      - backend
      - db
    image: 3-vidly_backend
    environment:
      DB_URL: mongodb://db/vidly # env variable, see variable sunbstitution link above as well
    command: npm test # ovewrites CMD of the dockerfile

  db:
    image: mongo:4.0-xenial # pulling image from dockerhub instead of bulding from dockerfile
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly: # No value, just property/volume name
